services:
  insight_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${DEV_ENVIRONMENT}
      - PORT=${PORT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    command: npm run dev
